version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 54320:5432
    volumes:
      - ./tools/db:/var/lib/postgresql/data